[build]
  command = "npm run build"
  publish = ".next"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[build.environment]
  NEXT_TELEMETRY_DISABLED = "1"

# Redirect all requests to Next.js
[[redirects]]
  from = "/*"
  to = "/"
  status = 200
  force = false
  conditions = {Role = ["admin"]}
